version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - "9006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_DATABASE=test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=test
      - PMA_PASSWORD=test
    depends_on:
      - db

  web:
    image: nginx:1.19.4-alpine
    ports:
      - '9080:80'
    depends_on:
      - app
    volumes:
      - ./public:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.composer-docker/cache:/root/.composer/cache
    depends_on:
      - db

